// <auto-generated />
using API_SERVICIOS.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_SERVICIOS.Migrations
{
    [DbContext(typeof(_DbContext))]
    [Migration("20211025191428_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API_SERVICIOS.Model.tb_clientes", b =>
                {
                    b.Property<long>("cliente_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cliente_direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cliente_dni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cliente_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cliente_nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cliente_tel_fjo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cliente_tel_mov")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cliente_id");

                    b.ToTable("Tb_libros");
                });
#pragma warning restore 612, 618
        }
    }
}
