// <auto-generated />
using API_SERVICIOS.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_SERVICIOS.Migrations
{
    [DbContext(typeof(_DbContext))]
    [Migration("20211025214915_01")]
    partial class _01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API_SERVICIOS.Model.tb_cargue", b =>
                {
                    b.Property<long>("cliente_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cargue_anio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_apr_cartera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_barrio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_carta_garantia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_cod_postal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_cod_servicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_cod_vendedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_consecutivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_cta_cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_equipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_est_orden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_factura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_factura_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_fec_atencion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_fec_compra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_fec_pago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_fec_reporte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_incidencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_lugar_compra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_mes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_pago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_ref_pago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_rer_armado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_serv_solic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_tecnico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_tel_fijo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargue_tel_mov")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cliente_id");

                    b.ToTable("Tb_Cargues");
                });

            modelBuilder.Entity("API_SERVICIOS.Model.tb_clientes", b =>
                {
                    b.Property<long>("cliente_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cliente_direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cliente_dni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cliente_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cliente_nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cliente_tel_fjo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cliente_tel_mov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cliente_tpo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cliente_id");

                    b.ToTable("Tb_Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
